+ __kick_off_join_feishu_group
- 大家好！我是你的 DevOps 助手机器人，在群里 @ 我或者私聊来找我，发送“帮助”或“help”获得使用介绍。

+ list projects
- ^getValidProjects()

+ create bug (*)
- ^createIssue(<cap1>,'bug')

+ create story (*)
- ^createIssue(<cap1>,'userstory')

+ create task (*)
- ^createIssue(<cap1>,'task')

+ create issue (*)
- ^createIssue(<cap1>)

+ close issue (*)
- ^closeIssue(<cap1>)

+ reopen issue (*)
- ^reopenIssue(<cap1>)